[[redirects]]
  from = "https://www.coins.yvogeldhof.nl/*"
  to = "https://coins.yvogeldhof.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.coins-yvogeldhof.netlify.app/*"
  to = "https://coins.yvogeldhof.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://coins-yvogeldhof.netlify.app/*"
  to = "https://coins.yvogeldhof.nl/:splat"
  status = 301
  force = true

